### ISSUE TITLE
Creation of send packet failed

### ISSUE THREAD

**Issue by ohmtrivedi** [zk7/hershelplus#1]
Hi,
I am trying to use hershelplus for OS fingerprinting and I am getting the following error:

`ohmtrivedi@ohmtrivedi-VirtualBox:~/Documents/ms-thesis-work/hershelplus$ sudo ./hershelplus 420OS_db.txt 420OS_mapping.txt 112.72.178.29 80
[sudo] password for ohmtrivedi: 
Reading from 420OS_db.txt...
Stored 21000 signatures in map
Starting Live fingerprinting of 112.72.178.29:80...
Listing system adapters:
1. enp0s3 at 10.0.2.15
2. lo at 127.0.0.1
Enter the adapter number between 1 and 2: 1
-----------------------------------------------
Opening device enp0s3
Adapter enp0s3 opened successfully
Local IP: 10.0.2.15
ioctl SIOCGARP failed! errno: 6
Creation of Send Packet failed
Error getting fingerprint
`
Being a newbie in Linux, can you kindly guide me as to what could be the problem? I am running the multi-platform version on Ubuntu VM on Oracle VirtualBox.

**Comment by zk7** [comment]
Looks like its having an issue trying to get the ARP request out to get the destination MAC. Do you have a gateway in your environment that can provide this? Check if the code is actually sending out an ARP request or if its failing before it gets there. 
If all else fails, if you know the destination MAC, you can hardcode it in and bypass the ioctl call.

**Comment by ohmtrivedi** [comment]
Sorry, I am not very experienced with C++. Can you suggest how do I check if the code is actually able to send ARP request or if it's failing before that?

I have a default gateway set on the Ubuntu VM. It uses the same gateway as the host OS (Windows 10). Is that what you asked?

**Comment by zk7** [comment]
You can use a tool like Wireshark to see the packets leaving your NIC. That way you can see if the ARP request is being sent, and if your gateway is responding correctly. 

Do you have your VM in bridged or NAT mode? I believe you will need bridged if you want to get responses from the same gateway your host OS has.

**Comment by ohmtrivedi** [comment]
Yes, I have set up my VM in bridged connection. Using Wireshark, I can see that the VM is able to send ARP packets. However, I do not see any captured traffic when I run hershelplus. Kindly refer to the attached screenshots.
![capture-1](https://user-images.githubusercontent.com/7829466/40929925-2db0a090-67f4-11e8-8b6d-018d2ed02e68.PNG)
![capture-2](https://user-images.githubusercontent.com/7829466/40929926-2dbee3f8-67f4-11e8-807d-58c9094b6da2.PNG)

Additionally, what I have observed is I am able to perform a successful ARP request on my LAN. Using 'arpsend' on Ubuntu, I was able to get MAC address of my host laptop. But, if I try to perform ARP request for some remote IPs on the Internet, I always get the same MAC as response (possibly of the gateway). Hope that helps in analysis.
![capture-3](https://user-images.githubusercontent.com/7829466/40991647-689e954e-68c2-11e8-8120-660e64cab144.PNG)

**Comment by zk7** [comment]
Right, the destination MAC should just be of the next hop (in this case your gateway) and it should stay the same as long as the destination is outside your LAN. This gateway MAC is the one which the ioctl SIOCGARP command seems to be failing to receive, I'm not sure why yet. 

As a temporary work around you can simply hard code this MAC into the `mac` variable and comment out the ioctl call. Its on this line: https://github.com/zk7/hershelplus/blob/dd6f37e54d77aee035a374fecee754322326d479/multi-platform/LiveFingerprinter.cpp#L604

**Comment by ohmtrivedi** [comment]
Do you happen to know how do I hard code the MAC in the `mac` variable? I mean should it be an array like `mac = ["38", "c3", "12", "c1", "ea", "32"]` or in some other data structure?

**Comment by ohmtrivedi** [comment]
Just to add if it helps, I am facing the same error on a Kali Linux distro as well. This distro runs on a remote server provided by my university.  So, on both distros (Ubuntu and Kali), I am able to execute the command `arpsend -D -e <remote-IP> <interface>` and gives me back the MAC address of my gateway (supposedly, since I use my university's network). But when I run the hershelplus program, I get `ioctl SIOCGARP failed! errno: 6`

**Comment by zk7** [comment]
Thanks for the info. Since its not working on multiple systems, I took a look around and it seems like using ioctl SIOCGARP just reads from the systems ARP table, so it is not the correct approach for this. I'll have to find another way to reliably get the destination MAC to fill into the packet. Unfortunately this seems like a pain to do in linux, but thanks for pointing out this bug.

Meanwhile, I think if you replace the destination MAC with zeros, it should still correctly send out the packet and get a response. I tested this on a quick VM setup. To do this, comment out this block: https://github.com/zk7/hershelplus/blob/dd6f37e54d77aee035a374fecee754322326d479/multi-platform/LiveFingerprinter.cpp#L600-L606
and add `memset(ehdr->dest, 0, MACADDRLEN);` 
Let me know if this works for you.

Also, to answer your previous question of hardcoding in your destination MAC, you can do it this way:
```
  mac[0] = 0x38;
  mac[1] = 0xc3;
  mac[2] = 0x12;
  mac[3] = 0xc1;
  mac[4] = 0xea;
  mac[5] = 0x32;
```

**Comment by zk7** [comment]
Just made some commits that I hope fixes the problem. Please test and see if it works.

**Comment by ohmtrivedi** [comment]
The workaround you suggested did work. But can you help me in explaining the output? For multiple different remote IPs, I am getting the same classification from the tool. Output was:

﻿ohmtrivedi@ohm-HP-ENVY:~/Documents/ms-thesis/hershelplus$ sudo ./hershelplus 420OS_db.txt 420OS_mapping.txt 124.164.24.92 80

Reading from 420OS_db.txt...
Stored 21000 signatures in map
Starting Live fingerprinting of 124.164.24.92:80...
Listing system adapters:

1. wlp1s0 at 10.12.117.43

2. enx00e151b0014d at 10.15.15.111

3. lo at 127.0.0.1

Enter the adapter number between 1 and 3: 1

-----------------------------------------------
Opening device wlp1s0
Adapter wlp1s0 opened successfully
Local MAC Address Is: 34:F6:4B:35:DE:78
Local IP: 10.12.117.43

Sending a SYN packet to 124.164.24.92 on port 80...
Listening for responses for 2 minutes (TCP Maximum Segment Life)...


Results appended to file fingerprints.txt
Signature being classified: 0,0,0,M,0,0,0,0,0,0

---Starting Hershel+ Classification---
**)bservation 0 classified as id 257 (PowerDSine Power View Pro**
---------------------------------------------------------------------------------------------------------------
ohmtrivedi@ohm-HP-ENVY:~/Documents/ms-thesis/hershelplus$ sudo ./hershelplus 420OS_db.txt 420OS_mapping.txt 160.202.40.106 80

Reading from 420OS_db.txt...
Stored 21000 signatures in map
Starting Live fingerprinting of 160.202.40.106:80...
Listing system adapters:

1. wlp1s0 at 10.12.117.43

2. enx00e151b0014d at 10.15.15.111

3. lo at 127.0.0.1

Enter the adapter number between 1 and 3: 1

-----------------------------------------------
Opening device wlp1s0
Adapter wlp1s0 opened successfully
Local MAC Address Is: 34:F6:4B:35:DE:78
Local IP: 10.12.117.43

Sending a SYN packet to 160.202.40.106 on port 80...
Listening for responses for 2 minutes (TCP Maximum Segment Life)...


Results appended to file fingerprints.txt
Signature being classified: 0,0,0,M,0,0,0,0,0,0

---Starting Hershel+ Classification---
**)bservation 0 classified as id 257 (PowerDSine Power View Pro**
---------------------------------------------------------------------------------------------------------------
ohmtrivedi@ohm-HP-ENVY:~/Documents/ms-thesis/hershelplus$ sudo ./hershelplus 420OS_db.txt 420OS_mapping.txt 188.3.1.188 8081

Reading from 420OS_db.txt...
Stored 21000 signatures in map
Starting Live fingerprinting of 188.3.1.188:8081...
Listing system adapters:

1. wlp1s0 at 10.12.117.43

2. enx00e151b0014d at 10.15.15.111

3. lo at 127.0.0.1

Enter the adapter number between 1 and 3: 2

-----------------------------------------------
Opening device enx00e151b0014d
Adapter enx00e151b0014d opened successfully
Local MAC Address Is: 00:E1:51:B0:01:4D
Local IP: 10.15.15.111

Sending a SYN packet to 188.3.1.188 on port 8081...
Listening for responses for 2 minutes (TCP Maximum Segment Life)...


Results appended to file fingerprints.txt
Signature being classified: 0,0,0,M,0,0,0,0,0,0

---Starting Hershel+ Classification---
**)bservation 0 classified as id 257 (PowerDSine Power View Pro**
---------------------------------------------------------------------------------------------------------------
ohmtrivedi@ohm-HP-ENVY:~/Documents/ms-thesis/hershelplus$ sudo ./hershelplus 420OS_db.txt 420OS_mapping.txt 186.32.55.31 80

Reading from 420OS_db.txt...
Stored 21000 signatures in map
Starting Live fingerprinting of 186.32.55.31:80...
Listing system adapters:

1. wlp1s0 at 10.12.117.43

2. enx00e151b0014d at 10.15.15.111

3. lo at 127.0.0.1

Enter the adapter number between 1 and 3: 2

-----------------------------------------------
Opening device enx00e151b0014d
Adapter enx00e151b0014d opened successfully
Local MAC Address Is: 00:E1:51:B0:01:4D
Local IP: 10.15.15.111

Sending a SYN packet to 186.32.55.31 on port 80...
Listening for responses for 2 minutes (TCP Maximum Segment Life)...


Results appended to file fingerprints.txt
Signature being classified: 0,0,0,M,0,0,0,0,0,0

---Starting Hershel+ Classification---
**)bservation 0 classified as id 257 (PowerDSine Power View Pro**

**Comment by zk7** [comment]
It looks like you are not receiving any packets from those targets. Make sure those services are up. I can add a simple check that ensures the classification only occurs if a response was seen.

**Comment by ohmtrivedi** [comment]
I am using nmap on the same remote IP and it does mention that service is up:

ohmtrivedi@ohm-HP-ENVY:~/Documents/ms-thesis/cve-web-scrap$ sudo nmap -sV -T5 -O -Pn 186.32.55.31
[sudo] password for ohmtrivedi: 

Starting Nmap 7.01 ( https://nmap.org ) at 2018-06-12 18:40 EDT
Warning: 186.32.55.31 giving up on port because retransmission cap hit (2).
Nmap scan report for 186.32.55.31
Host is up (0.087s latency).
All 1000 scanned ports on 186.32.55.31 are closed (964) or filtered (36)
Warning: OSScan results may be unreliable because we could not find at least 1 open and 1 closed port
Device type: general purpose
Running: Linux 2.6.X
OS CPE: cpe:/o:linux:linux_kernel:2.6.18
OS details: Linux 2.6.18, Linux 2.6.30
Network Distance: 13 hops

OS and Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 32.55 seconds

But at the same time, hershelplus gives the following:

ohmtrivedi@ohm-HP-ENVY:~/Documents/ms-thesis/hershelplus/multi-platform$  sudo ./hershelplus 420OS_db.txt 420OS_mapping.txt 186.32.55.31 80

Reading from 420OS_db.txt...
Stored 21000 signatures in map
Starting Live fingerprinting of 186.32.55.31:80...
Listing system adapters:

1. wlp1s0 at 10.12.190.204

2. enx00e151b0014d at 10.15.15.111

3. lo at 127.0.0.1

Enter the adapter number between 1 and 3: 2

-----------------------------------------------
Opening device enx00e151b0014d
Adapter enx00e151b0014d opened successfully
Local IP: 10.15.15.111
Gateway IP: 10.15.14.1

Sending a SYN packet to 186.32.55.31 on port 80...
Listening for responses for 2 minutes (TCP Maximum Segment Life)...


Results appended to file fingerprints.txt

---Starting Hershel+ Classification on 1 observation(s)---
Observed signature: 0,0,0,M,0,0,0,0,0,0
Matching signature: 0,64,0,X,0,0,0,0,0,0,0.000000,0.000000
 	Observation 0 classified as PowerDSine Power View Pro

**Comment by zk7** [comment]
The host is up, but the port is filtered/closed.

From your output:
> Host is up (0.087s latency).
> All 1000 scanned ports on 186.32.55.31 are closed (964) or filtered (36)

**Comment by ohmtrivedi** [comment]
So the specified port should be strictly opened for OS fingerprinting in case of hershel's classification?

**Comment by zk7** [comment]
Yes, there needs to be a TCP based service running on the port that will respond to the hershel probe.
Since the code is working now, I will go ahead and close this issue. Thanks for reporting the bug.
